"""Compatibility exports for the backend-owned command registry."""

from bot.command_registry import (
    BASE_COMMAND_GROUPS,
    HIDDEN_SHARED_COMMANDS,
    LEAGUE_COMMANDS,
    OVERWATCH_COMMANDS,
    SHARED_COMMAND_DEFINITIONS,
    CommandAvailability,
    CommandDefinition,
    CommandGroupDefinition,
    CommandHelpGroup,
    CommandHelpItem,
    CommandPermission,
    CommandSlowmode,
    CommandVisibility,
    build_command_help_groups,
    build_enabled_command_help_groups,
    build_points_group,
    command_is_enabled,
    get_profile_command_groups,
    get_registered_definitions,
    get_shared_command_definitions,
    validate_command_definitions,
)

__all__ = (
    "BASE_COMMAND_GROUPS",
    "HIDDEN_SHARED_COMMANDS",
    "LEAGUE_COMMANDS",
    "OVERWATCH_COMMANDS",
    "SHARED_COMMAND_DEFINITIONS",
    "CommandAvailability",
    "CommandDefinition",
    "CommandGroupDefinition",
    "CommandHelpGroup",
    "CommandHelpItem",
    "CommandPermission",
    "CommandSlowmode",
    "CommandVisibility",
    "build_command_help_groups",
    "build_enabled_command_help_groups",
    "build_points_group",
    "command_is_enabled",
    "get_profile_command_groups",
    "get_registered_definitions",
    "get_shared_command_definitions",
    "validate_command_definitions",
)
